  !constants
  real*8, parameter :: sigma0 =	1.761d-44 !cm^2
  real*8, parameter :: Gfermi = 1.16637d-11 !MeV^-2
  real*8, parameter :: gA = 1.254d0 !dimensionless
  real*8, parameter :: delta_np = 1.293332d0 !MeV
  real*8, parameter :: m_e = 0.510998910d0  !MeV
  real*8, parameter :: m_e_x2 = (0.510998910d0)**2 !MeV^2
  real*8, parameter :: m_n = 939.565346d0 !MeV
  real*8, parameter :: m_p = 938.272013d0 !MeV
  real*8, parameter :: m_amu =  931.494061d0 !MeV
  real*8, parameter :: m_pi =  139.57018d0 !MeV
  real*8, parameter :: m_alpha = 3727.379240 !MeV
  real*8, parameter :: sin2thetaW = 0.23d0 !dimensionless
  real*8, parameter :: clight = 29979245800.0d0 !cm/s
  real*8, parameter :: pi = 3.141592653589793238462643383279d0
  real*8, parameter :: hbarc_ergcm = 3.1615262d-17! in erg*cm
  real*8, parameter :: hbarc_mevcm = 1.97326966d-11! in MeV*cm
  real*8, parameter :: FSC = 7.2973525376d-3 !dimensionless
  real*8, parameter :: log10exp = 0.43429448190325182765 !dimensionless = log_{10}(exp(1))
  real*8, parameter :: planck = 6.626176d-27 !h (i.e. hbar*2*pi), in cgs
  real*8, parameter :: avo = 6.0221367d23 !N_A, avogadro's number


  !conversions
  real*8, parameter :: mev_to_gram = 1.782661758d-27 !one MeV is # grams
  real*8, parameter :: mev_to_erg = 1.60217733d-6 !one MeV is # ergs
  real*8, parameter :: kelvin_to_mev = 8.6173423d-11 !one K is # MeV


